version: "3.12"

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  api:
    build: .
    container_name: integration-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - .:/app
    depends_on:
      - mongo

volumes:
  mongodb_data:
